### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by pedroalbanese** [dgryski/go-krcrypt#2]
Greetings!!

Hi Damian, my name is Pedro Albanese, I'm an admirer of your work and a user of your libraries. I would like to know if it is possible to implement the Anubis algorithm, by Paulo Barreto and Vincent Rijmen. I couldn't help but notice that you are at ease with unconventional algorithms. In Brazil we only have Whirlpool also by Paulo Barreto and Vincent Rijmen, we lack a block cipher.

There is an implementation in C, I believe it is not difficult to port to Golang, I myself would be incapable of such a feat..
https://github.com/mkj/dropbear/blob/master/libtomcrypt/src/ciphers/anubis.c

Please help us! 

Thanks in advance.

**Comment by dgryski** [comment]
I'm working on an anubis implementation. I'll update you here when it's done.

**Comment by pedroalbanese** [comment]
Thank you!

**Comment by dgryski** [comment]
Sorry, realized I never pushed my implementation to github: https://github.com/dgryski/go-anubis

**Comment by pedroalbanese** [comment]
Is perfect!! Thank you very much!!

**Comment by pedroalbanese** [comment]
Hey Damian, forgive my ignorance, but how to convert *cast5.Cipher end *anubis.Cipher to cipher.Block? (for PEM encryption)
